# Generated by Django 5.1.2 on 2024-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'urls',
            },
        ),
    ]
